
# This is a configuration file for the bacon tool
# More info at https://github.com/Canop/bacon

default_job = "check"

[jobs]

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--tests", "--color", "always"]
need_stdout = false

[jobs.light]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--color", "always"]
need_stdout = false

[jobs.clippy_no_default_features]
command = ["cargo", "clippy", "--color", "always", "--no-default-features"]
need_stdout = false

[jobs.test]
command = ["cargo", "test", "--color", "always"]
need_stdout = true

[jobs.test_no_default_features]
command = ["cargo", "test", "--color", "always", "--no-default-features"]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc"]
need_stdout = true
