[package]
name = "format_serde_error"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"

[dev-dependencies]
anyhow = "1"
pretty_assertions = "0.7"
